title: "Subharshi Roy"
name: "Subharshi Roy"
description: "Research @IITD | Weaving compute into surreal dreamscapes"
baseurl: "" 
url: "https://subharshitect.github.io"

theme: "ai-folio"

lang: "en"
favicon: "assets/img/avatar.jpg"  # Replace with your own image
avatar: "assets/img/avatar.jpg"   # Your photo (put it here)

# Minimal site settings
header_pages: []

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional extras (disable everything else)
show_social_links: false
show_about: false
show_projects: false
show_blog: false
show_publications: false
show_contact: false

dark_theme: true
